Repository heysaiyad/Hacktoberfest2023-DSA, pull requests merged in 2023-10, with the labels that each got.

#10 PR Request For Adding New Array DSA Problem
  04. Arrays/7_Find the closest pair from two arrays.cpp
Labels: hacktoberfest

#13 Added Decode_String.cpp
  09. String/01 Problem Name.txt
  09. String/02_Decode_String.cpp
  CONTRIBUTING.md
Labels: hacktoberfest

#21 find Middleelementlinkedlist.cpp
  10. Linked List/Middleelementlinkedlist.cpp
Labels: hacktoberfest

#28 Added Leetcode Reverse of Number Algorithm in CPP
  Reverse of Number/main.cpp
Labels: hacktoberfest

#22 Missingnumber.cpp
  04. Arrays/Missingnumber.cpp
Labels: Hacktoberfest-accepted

#175 Implemented Menu Driven Program for Stack using Arrays with Manual and Automated Testing using Junit
  11. Stack/01 Problem Name.txt
Labels: hacktoberfest, Hacktoberfest-accepted

#174 added a Nth Fibonacci Number solution in cpp
  20. Dynamic Programming/Nth Fibonacci Number.cpp
Labels: Hacktoberfest-accepted

#173 Shuvradipsarma vitb patch 1
  maze.java
  maze_exit.java
Labels: Hacktoberfest-accepted

#176 C++ Programme to calculate Factorial
  01. Mathematics/factorial.cpp
Labels: Hacktoberfest-accepted

#172 Create RemoveKth.cpp
  10. Linked List/RemoveKth.cpp
Labels: Hacktoberfest-accepted

#170 Create coin_change.cpp
  20. Dynamic Programming/coin_change.cpp
Labels: Hacktoberfest-accepted

#169 Created SudokuSolver.cpp Leet 37 [Hard]
  19. Backtracking/SudokuSolver.cpp
Labels: Hacktoberfest-accepted

#164 Added related programs
  06. Sorting/Heap_Sort.c
  06. Sorting/Insertion_Bubble_Selection_Count_Sort.c
  06. Sorting/Quick_Sort_Merge_Sort.c
  10. Linked List/Circular_Linked_LIst.c
  10. Linked List/Double_Linked_List.c
  10. Linked List/Queue_Linked_List.c
  10. Linked List/Stack_Linked_List.c
  11. Stack/Stacks_Implementation.c
  12. Queue/Queue_Implementation.c
  14. Tree/Binary_Trees.c
  14. Tree/Expression_Tree.c
  15. Binary Search Tree/Binary_Search_Trees_Implementation.c
Labels: Hacktoberfest-accepted

#178 Added some basic Algorithms for Binary Search
  .idea/.gitignore
  .idea/Hacktoberfest2023-DSA.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  05. Searching/.idea/.gitignore
  05. Searching/.idea/05. Searching.iml
  05. Searching/.idea/misc.xml
  05. Searching/.idea/modules.xml
  05. Searching/.idea/uiDesigner.xml
  05. Searching/.idea/vcs.xml
  05. Searching/01 Problem Name.txt
  05. Searching/Binary Search/.idea/.gitignore
  05. Searching/Binary Search/.idea/misc.xml
  05. Searching/Binary Search/.idea/modules.xml
  05. Searching/Binary Search/.idea/vcs.xml
  05. Searching/Binary Search/1.Binary Search.txt
  05. Searching/Binary Search/Binary Search.iml
  05. Searching/Binary Search/BinarySearch.java
  05. Searching/Binary Search/BinarySearch2D.java
  05. Searching/Binary Search/BinarySearchRotated.java
  05. Searching/Binary Search/BinarysearchCeiling.java
  05. Searching/Binary Search/BinarysearchFloor.java
  05. Searching/Binary Search/out/production/05. Searching/.idea/.gitignore
  05. Searching/Binary Search/out/production/05. Searching/.idea/05. Searching.iml
  05. Searching/Binary Search/out/production/05. Searching/.idea/misc.xml
  05. Searching/Binary Search/out/production/05. Searching/.idea/modules.xml
  05. Searching/Binary Search/out/production/05. Searching/.idea/vcs.xml
  05. Searching/Binary Search/out/production/05. Searching/1.Binary Search.txt
  05. Searching/Binary Search/out/production/05. Searching/ProblemStatement1.class
  05. Searching/Binary Search/out/production/05. Searching/ProblemStatement2.class
  05. Searching/Binary Search/out/production/05. Searching/ProblemStatement3.class
  05. Searching/Binary Search/out/production/Binary Search/.idea/.gitignore
  05. Searching/Binary Search/out/production/Binary Search/.idea/misc.xml
  05. Searching/Binary Search/out/production/Binary Search/.idea/modules.xml
  05. Searching/Binary Search/out/production/Binary Search/.idea/vcs.xml
  05. Searching/Binary Search/out/production/Binary Search/1.Binary Search.txt
  05. Searching/Binary Search/out/production/Binary Search/Binary Search.iml
  05. Searching/Binary Search/out/production/Binary Search/BinarySearch.class
  05. Searching/Binary Search/out/production/Binary Search/BinarySearch2D.class
  05. Searching/Binary Search/out/production/Binary Search/BinarySearchRotated.class
  05. Searching/Binary Search/out/production/Binary Search/BinarysearchCeiling.class
  05. Searching/Binary Search/out/production/Binary Search/BinarysearchFloor.class
Labels: hacktoberfest, Hacktoberfest-accepted

#218 Create odd even linked list.cpp
  10. Linked List/odd even linked list.cpp
Labels: hacktoberfest, Hacktoberfest-accepted

#220 Added Djikstra's Algorithm. Closes Issue #219
  17. Graph/Dijkstra'sAlgorithm.cpp
Labels: hacktoberfest, Hacktoberfest-accepted

#23 Create Binarysearch.cpp
  05. Searching/Binarysearch.cpp
Labels: hacktoberfest, Hacktoberfest-accepted

#297 Added Stack problems
  11. Stack/ArrayImplementStack.cpp
  11. Stack/Basic_Calculator.cpp
  11. Stack/Brackets Validator.cpp
Labels: Hacktoberfest-accepted

#260 Created mergesort.java
  06. Sorting/mergesort.java
  10. Linked List/doublylinkedlist.java
Labels: Hacktoberfest-accepted

#256 Added Dijkstra's Algorithm in java
  17. Graph/Dijkstra'sAlgorithm.java
Labels: Hacktoberfest-accepted

#255 Create 0-1-Knapsack-Problem.cpp
  20. Dynamic Programming/0-1-Knapsack-Problem.cpp
Labels: Hacktoberfest-accepted

#251 Create TopologicalSortBFS.cpp
  17. Graph/TopologicalSortBFS.cpp
Labels: hacktoberfest-accepted

#250 Adding a file of Merge Sort in Java
  06. Sorting/MergeSort.java
Labels: hacktoberfest-accepted

#248 Recursion and BitMagic problem added along with solutuion
  02. Bit Magic/01 Problem Name.txt
  02. Bit Magic/SubarrayIndex.java
  02. Bit Magic/module-info.java
  03. Recursion/01 Problem Name.txt
  03. Recursion/CheckSorted.java
Labels: hacktoberfest-accepted

#267 Create DuplicateWordCount.java
  09. String/DuplicateWordCount.java
Labels: hacktoberfest-accepted

#316 Word-Ladder(Leetcode - C++)
  17. Graph/Word-Ladder/word-ladder.cpp
  17. Graph/Word-Ladder/word-ladder.md
Labels: hacktoberfest-accepted
